export const portfolioItems = [
  {
    id: 1,
    title: 'Riverside Auto Group — Lot Walk Series',
    category: 'Short-Form Video',
    views: '2.4M',
    platform: 'TikTok',
    thumbnail: null,
  },
  {
    id: 2,
    title: 'Sunstate Ford — F-150 Launch',
    category: 'Paid Ads Creative',
    views: '800K',
    platform: 'Instagram',
    thumbnail: null,
  },
  {
    id: 3,
    title: 'Premier Honda — Monthly Promotion',
    category: 'Social Media Campaign',
    views: '1.1M',
    platform: 'Instagram + TikTok',
    thumbnail: null,
  },
  {
    id: 4,
    title: 'Desert Motors — Behind the Deal',
    category: 'Short-Form Video',
    views: '3.2M',
    platform: 'TikTok',
    thumbnail: null,
  },
  {
    id: 5,
    title: 'Gateway BMW — Luxury Showcase',
    category: 'Content Series',
    views: '650K',
    platform: 'YouTube Shorts',
    thumbnail: null,
  },
  {
    id: 6,
    title: 'Capital Chevrolet — Trade-In Campaign',
    category: 'Lead Gen System',
    views: '420K',
    platform: 'Meta Ads',
    thumbnail: null,
  },
]
