export const plans = [
  {
    id: 'starter',
    name: 'Starter',
    price: 1500,
    period: '/mo',
    tagline: 'Get your dealership on the map',
    isPopular: false,
    features: [
      '8 short-form videos per month',
      'Instagram + TikTok management',
      'Monthly content calendar',
      'Basic performance reporting',
      'Caption & hashtag strategy',
      'Email support',
    ],
    cta: 'Get Started',
  },
  {
    id: 'growth',
    name: 'Growth',
    price: 3500,
    period: '/mo',
    tagline: 'For dealerships ready to dominate',
    isPopular: true,
    features: [
      '20 short-form videos per month',
      'Full platform management (IG, TikTok, FB, YT)',
      'Paid ads creative (4 ads/mo)',
      'Lead generation funnel setup',
      'Bi-weekly strategy calls',
      'Weekly performance reports',
      'CRM integration support',
      'Priority support',
    ],
    cta: 'Book a Call',
  },
  {
    id: 'elite',
    name: 'Elite',
    price: 7500,
    period: '/mo',
    tagline: 'Full-scale content dominance',
    isPopular: false,
    features: [
      'Unlimited content production',
      'All platforms + YouTube long-form',
      'Full paid ads management',
      'Dedicated account strategist',
      'Weekly 1:1 strategy sessions',
      'Real-time analytics dashboard',
      'Influencer & collab outreach',
      'White-glove onboarding',
      '24/7 priority support',
    ],
    cta: 'Book a Call',
  },
]
